export const GET_CATEGORIES_REQUESTED = 'GET_CATEGORIES_REQUESTED'
export const SET_GET_CATEGORIES_REQUESTED = 'SET_GET_CATEGORIES_REQUESTED'

export const SEARCH_PRODUCTS_BY_NAME_REQUESTED = 'SEARCH_PRODUCTS_BY_NAME_REQUESTED'
export const SET_SEARCH_PRODUCTS_BY_NAME_REQUESTED = 'SET_SEARCH_PRODUCTS_BY_NAME_REQUESTED'

export const GET_USER_DETAILS_REQUESTED = 'GET_USER_DETAILS_REQUESTED'
export const SET_USER_DETAILS_REQUESTED = 'SET_USER_DETAILS_REQUESTED'

export const CHANGE_CART_ID = 'CHANGE_CART_ID'