export const GET_CATEGORIES_REQUESTED = 'GET_CATEGORIES_REQUESTED'
export const SET_GET_CATEGORIES_REQUESTED = 'SET_GET_CATEGORIES_REQUESTED'

// export const GET_CATEGORIES_REQUESTED_ASYNC = 'GET_CATEGORIES_REQUESTED_ASYNC'
