export const GET_CATEGORIES_REQUESTED = 'GET_CATEGORIES_REQUESTED'
export const SET_GET_CATEGORIES_REQUESTED = 'SET_GET_CATEGORIES_REQUESTED'

export const SEARCH_PRODUCTS_BY_NAME_REQUESTED = 'SEARCH_PRODUCTS_BY_NAME_REQUESTED'
export const SET_SEARCH_PRODUCTS_BY_NAME_REQUESTED = 'SET_SEARCH_PRODUCTS_BY_NAME_REQUESTED'
